### ISSUE TITLE
Example, please...

### ISSUE THREAD

**Issue by n0ne** [zoover/react-redux-i18n#1]
Hi.
Please, one small example...One small example is better then 100 words...

**Comment by tikider** [comment]
Hi.
I added more details to the readme file. I hope it is clearer now. if you still need any clarifications please let me know.

**Comment by n0ne** [comment]
Looks great, thank you (-:

I've just finished some experiments with react-i18nify and now need some time for experiments with react-redux-i18n.

Small question: can I load translateObject in each Component? Or  it have to be smth global?

**Comment by tikider** [comment]
You just need to load it once, and it will live in your redux store; from which the translation operation and components will get all needed translations from. That's it!
`store.dispatch(loadTranslations(translationsObject);`

So you do not need to load the translation object in any component, you just import the translation components and provide strings to be translated.

**Comment by n0ne** [comment]
Hi again!
I have no idea, why my `store.i18n` is empty after these lines:

     syncTranslationWithStore(store)
     store.dispatch(loadTranslations(translatesObject)); 
     store.dispatch(setLocale('en'));

`translatesObject` looks normal, but nothing works......any suggestions?
