### ISSUE TITLE
update locale at runtime

### ISSUE THREAD

**Issue by zjjt** [zoover/react-redux-i18n#2]
Hi there your work is really cool..But i have an issue.i have to issue an action which changes the locale at runtime.the action fires correctly and changes the state tree accordingly but the view isnt updated unless i refresh the page.Is there a way to achieve this dynamically? thank you

**Comment by fliptv97** [comment]
This feature really need me in project

**Comment by tikider** [comment]
Are you sure that a re-render occurs when you change the state? are you using react-redux also?

**Comment by zjjt** [comment]
Yes i do use react-redux...but i finally got it working...by using the mapStatetoProps function...i was doing something the wrong way with my code that didnt trigger the re-rendering but i fixed it somehow.now it changes on the fly

**Comment by tikider** [comment]
Nice to hear!
