### ISSUE TITLE
It will not work in the next major version of React

### ISSUE THREAD

**Issue by jagajagachan** [zoover/react-redux-i18n#6]
Thanks for your great i18n library.
I tried  and worked fine.
But I have the following warning message on Google Chrome Console.
Could you confirm that?

> Warning: You are manually calling a React.PropTypes validation function for the `value` prop on `t`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

**Comment by gerbenmeyer** [comment]
Which React version are you using? This seems to be the same issue as here https://github.com/zoover/react-i18nify/issues/4, and there it was resolved with updating the project dependencies.

**Comment by jagajagachan** [comment]
Thanks for your advice
My issue solved when updating React's latest version :)
👍 

```
react                    ^0.14.7  →  ^15.3.1 
react-dom                ^0.14.7  →  ^15.3.1 
```
